from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, Float, func
from sqlalchemy.orm import relationship
from app.core.database import Base


class QuizQuestion(Base):
    """A single MCQ question generated by AI for a Learning Space."""
    __tablename__ = "quiz_questions"

    id = Column(Integer, primary_key=True, index=True)
    space_id = Column(Integer, ForeignKey("learning_spaces.id", ondelete="CASCADE"), nullable=False, index=True)
    topic = Column(String, nullable=False)             # e.g. "Newton's Laws"
    source_type = Column(String, nullable=False, server_default="curriculum")  # "curriculum" or "user"
    question = Column(Text, nullable=False)
    option_a = Column(Text, nullable=False)
    option_b = Column(Text, nullable=False)
    option_c = Column(Text, nullable=False)
    option_d = Column(Text, nullable=False)
    correct_option = Column(String(1), nullable=False)  # "a", "b", "c", or "d"
    explanation = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    attempts = relationship("QuizAttempt", back_populates="question", cascade="all, delete-orphan")


class QuizSession(Base):
    """Represents a single quiz taking session (mock exam or practice)."""
    __tablename__ = "quiz_sessions"

    id = Column(Integer, primary_key=True, index=True)
    space_id = Column(Integer, ForeignKey("learning_spaces.id", ondelete="CASCADE"), nullable=False, index=True)
    topic = Column(String, nullable=True)               # None means full syllabus
    source_type = Column(String, nullable=False, server_default="curriculum")  # "curriculum" or "user"
    total_questions = Column(Integer, nullable=False)
    correct_answers = Column(Integer, nullable=False, default=0)
    score_pct = Column(Integer, nullable=False, default=0)
    is_exam = Column(Boolean, nullable=False, default=False)
    lang = Column(String, nullable=False, default="en")
    is_completed = Column(Boolean, nullable=False, default=False)
    user_id = Column(Integer, index=True, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    attempts = relationship("QuizAttempt", back_populates="session", cascade="all, delete-orphan")
    analysis = relationship("PerformanceAnalysis", back_populates="session", uselist=False, cascade="all, delete-orphan")


class QuizAttempt(Base):
    """Records a user's answer to a single MCQ."""
    __tablename__ = "quiz_attempts"

    id = Column(Integer, primary_key=True, index=True)
    space_id = Column(Integer, ForeignKey("learning_spaces.id", ondelete="CASCADE"), nullable=False, index=True)
    session_id = Column(Integer, ForeignKey("quiz_sessions.id", ondelete="CASCADE"), nullable=True, index=True)
    question_id = Column(Integer, ForeignKey("quiz_questions.id", ondelete="CASCADE"), nullable=False)
    user_answer = Column(String(1), nullable=False)     # "a", "b", "c", or "d"
    is_correct = Column(Boolean, nullable=False)
    time_taken_seconds = Column(Integer, nullable=True)
    is_exam = Column(Boolean, nullable=False, default=False)  # True if from Exam Lab
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    question = relationship("QuizQuestion", back_populates="attempts")
    session = relationship("QuizSession", back_populates="attempts")


class PerformanceAnalysis(Base):
    """Stores the generated performance analysis for a completed quiz session."""
    __tablename__ = "performance_analyses"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("quiz_sessions.id", ondelete="CASCADE"), nullable=False, index=True, unique=True)
    space_id = Column(Integer, ForeignKey("learning_spaces.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(Integer, index=True, nullable=True)

    # Deterministic fields
    performance_level = Column(String, nullable=False)
    total_questions = Column(Integer, nullable=False)
    correct_count = Column(Integer, nullable=False)
    incorrect_count = Column(Integer, nullable=False)
    skipped_count = Column(Integer, nullable=False)
    score_pct = Column(Float, nullable=False)

    # JSON blobs stored as TEXT
    strong_areas = Column(Text, nullable=True)
    developing_areas = Column(Text, nullable=True)
    priority_areas = Column(Text, nullable=True)
    topic_insights = Column(Text, nullable=True)
    mistake_patterns = Column(Text, nullable=True)
    recommendations = Column(Text, nullable=True)

    # AI-generated fields
    overall_summary = Column(Text, nullable=True)
    ai_narrative = Column(Text, nullable=True)
    ai_generated = Column(Boolean, nullable=False, default=False)

    # Metadata
    analysis_version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    session = relationship("QuizSession", back_populates="analysis")
