import { useState, useEffect, useRef } from 'react'
import { Loader2, Timer, ChevronRight, CheckCircle, XCircle, AlertTriangle } from 'lucide-react'
import { quizService } from '../../services/quizService'
import type { QuizQuestion } from '../../types/quiz'

interface ExamLabTabProps {
  spaceId: number
  subject: string
  examId: string
}

type Phase = 'setup' | 'exam' | 'results'

const OPTION_KEYS = ['a', 'b', 'c', 'd'] as const
type OptionKey = typeof OPTION_KEYS[number]

const PRESETS = [
  { label: '10 Questions', count: 10, duration: 10 },
  { label: '20 Questions', count: 20, duration: 20 },
  { label: '30 Questions', count: 30, duration: 40 },
]

export default function ExamLabTab({ spaceId, subject, examId }: ExamLabTabProps) {
  const [topic, setTopic] = useState('')
  const [preset, setPreset] = useState(0)
  const [phase, setPhase] = useState<Phase>('setup')
  const [questions, setQuestions] = useState<QuizQuestion[]>([])
  const [answers, setAnswers] = useState<Record<number, OptionKey>>({})     // questionId → answer
  const [current, setCurrent] = useState(0)
  const [timeLeft, setTimeLeft] = useState(0)
  const [loading, setLoading] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [results, setResults] = useState<{ correct: number; total: number; breakdown: { q: QuizQuestion; answer: OptionKey | null; correct: boolean }[] } | null>(null)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // Timer countdown during exam
  useEffect(() => {
    if (phase !== 'exam') return
    timerRef.current = setInterval(() => {
      setTimeLeft((t) => {
        if (t <= 1) {
          clearInterval(timerRef.current!)
          finishExam()
          return 0
        }
        return t - 1
      })
    }, 1000)
    return () => clearInterval(timerRef.current!)
  }, [phase])

  const formatTime = (s: number) => {
    const m = Math.floor(s / 60)
    const sec = s % 60
    return `${m}:${sec.toString().padStart(2, '0')}`
  }

  const handleStart = async () => {
    if (!topic.trim()) return
    setLoading(true)
    setError(null)
    try {
      const { count, duration } = PRESETS[preset]
      const qs = await quizService.generate(spaceId, { topic: topic.trim(), count })
      setQuestions(qs)
      setAnswers({})
      setCurrent(0)
      setTimeLeft(duration * 60)
      setPhase('exam')
    } catch (e: any) {
      setError(e?.response?.data?.detail ?? e?.message ?? 'Failed to generate exam questions')
    } finally {
      setLoading(false)
    }
  }

  const finishExam = async () => {
    clearInterval(timerRef.current!)
    setSubmitting(true)

    // Submit all answers
    let correct = 0
    const breakdown: { q: QuizQuestion; answer: OptionKey | null; correct: boolean }[] = []

    for (const q of questions) {
      const answer = answers[q.id] ?? null
      let isCorrect = false
      if (answer) {
        try {
          const res = await quizService.submitAnswer(spaceId, {
            question_id: q.id,
            user_answer: answer,
            is_exam: true,
          })
          isCorrect = res.is_correct
        } catch { /* skip failed submissions */ }
      }
      if (isCorrect) correct++
      breakdown.push({ q, answer, correct: isCorrect })
    }

    setResults({ correct, total: questions.length, breakdown })
    setPhase('results')
    setSubmitting(false)
  }

  // ── Setup ─────────────────────────────────────────────────────────────────
  if (phase === 'setup') {
    return (
      <div className="max-w-lg mx-auto px-4 py-12">
        <h2 className="text-lg font-semibold text-white mb-1">Exam Lab</h2>
        <p className="text-slate-400 text-sm mb-8">
          Take a timed mock exam. Questions are generated by AI for your topic.
        </p>

        <div className="space-y-5">
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1.5" htmlFor="exam-topic">Topic</label>
            <input
              id="exam-topic"
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder={`e.g. Thermodynamics, Cell Biology…`}
              className="input-field"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">Exam Mode</label>
            <div className="grid grid-cols-3 gap-2">
              {PRESETS.map((p, i) => (
                <button
                  key={i}
                  id={`preset-${i}`}
                  onClick={() => setPreset(i)}
                  className={`py-3 px-2 rounded-xl border text-sm text-center transition-all ${
                    preset === i
                      ? ''
                      : 'border-white/10 bg-white/[0.03] text-slate-400 hover:border-white/20'
                  }`}
                  style={preset === i ? { backgroundColor: 'var(--accent-soft)', borderColor: 'rgba(90,127,245,0.2)', color: 'var(--accent)' } : undefined}
                >
                  <div className="font-medium text-current">{p.count} Qs</div>
                  <div className="text-xs text-slate-500 mt-0.5">{p.duration} min</div>
                </button>
              ))}
            </div>
          </div>

          {error && <p className="text-red-400 text-sm">{error}</p>}

          <button
            id="start-exam-btn"
            onClick={handleStart}
            disabled={!topic.trim() || loading}
            className="btn-primary w-full justify-center disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating Exam…</> : <>Start Exam <Timer className="w-4 h-4" /></>}
          </button>
        </div>
      </div>
    )
  }

  // ── Results ───────────────────────────────────────────────────────────────
  if (phase === 'results' && results) {
    const pct = Math.round((results.correct / results.total) * 100)
    return (
      <div className="max-w-2xl mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <div className="text-4xl mb-3">{pct >= 70 ? '🏆' : pct >= 40 ? '📖' : '💪'}</div>
          <h2 className="text-xl font-bold text-white mb-1">Exam Complete</h2>
          <p className="text-slate-400 text-sm">Topic: {questions[0]?.topic}</p>
          <div className="mt-4 inline-flex items-center gap-6 glass-card rounded-2xl px-8 py-4">
            <div className="text-center">
              <div className="text-3xl font-bold text-white">{results.correct}/{results.total}</div>
              <div className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>Score</div>
            </div>
            <div className="w-px h-8" style={{ backgroundColor: 'var(--border)' }} />
            <div className="text-center">
              <div className="text-3xl font-bold text-white">{pct}%</div>
              <div className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>Accuracy</div>
            </div>
          </div>
        </div>

        <h3 className="text-sm font-medium text-slate-300 mb-4">Answer Key</h3>
        <div className="space-y-3">
          {results.breakdown.map((item, i) => (
            <div key={item.q.id} className={`rounded-xl p-4 border text-sm ${
              item.correct ? 'border-emerald-500/20 bg-emerald-500/5' : 'border-red-500/20 bg-red-500/5'
            }`}>
              <div className="flex items-start gap-3">
                {item.correct
                  ? <CheckCircle className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
                  : <XCircle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                }
                <div className="flex-1 min-w-0">
                  <p className="text-slate-200 mb-1">Q{i + 1}. {item.q.question}</p>
                  <p className="text-xs text-slate-400">
                    Your answer: <span className={item.correct ? 'text-emerald-400' : 'text-red-400'}>
                      ({item.answer?.toUpperCase() ?? '—'}) {item.answer ? (item.q as any)[`option_${item.answer}`] : 'Not answered'}
                    </span>
                  </p>
                  {!item.correct && (
                    <p className="text-xs text-emerald-400 mt-0.5">
                      Correct: ({item.q.correct_option.toUpperCase()}) {(item.q as any)[`option_${item.q.correct_option}`]}
                    </p>
                  )}
                  {item.q.explanation && (
                    <p className="text-xs text-slate-500 mt-1 italic">{item.q.explanation}</p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>

        <button
          id="new-exam-btn"
          onClick={() => { setPhase('setup'); setTopic('') }}
          className="btn-outline w-full justify-center mt-6"
        >
          Take Another Exam
        </button>
      </div>
    )
  }

  // ── Exam in progress ───────────────────────────────────────────────────────
  if (submitting) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-4">
        <Loader2 className="w-8 h-8 animate-spin" style={{ color: 'var(--accent)' }} />
        <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Submitting your answers…</p>
      </div>
    )
  }

  const q = questions[current]
  const optionLabels: Record<OptionKey, string> = {
    a: q.option_a, b: q.option_b, c: q.option_c, d: q.option_d,
  }
  const answered = Object.keys(answers).length
  const isTimeCritical = timeLeft < 60

  return (
    <div className="max-w-2xl mx-auto px-4 py-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <span className="text-slate-400 text-sm">Q {current + 1}/{questions.length} · {answered} answered</span>
        <div className={`flex items-center gap-1.5 text-sm font-mono font-medium px-3 py-1 rounded-lg ${
          isTimeCritical ? 'bg-red-500/15 border border-red-500/30 text-red-400' : 'bg-white/5 border border-white/10 text-slate-300'
        }`}>
          {isTimeCritical && <AlertTriangle className="w-3.5 h-3.5" />}
          <Timer className="w-3.5 h-3.5" />
          {formatTime(timeLeft)}
        </div>
      </div>

      {/* Progress dots */}
      <div className="flex gap-1 flex-wrap mb-6">
        {questions.map((qq, i) => (
          <button
            key={qq.id}
            onClick={() => setCurrent(i)}
            className={`w-6 h-6 rounded text-xs font-medium transition-colors ${
              i === current ? 'text-white' :
              answers[qq.id] ? 'bg-emerald-500/30 text-emerald-400 border border-emerald-500/40' :
              'bg-white/5 text-slate-500 hover:bg-white/10'
            }`}
            style={i === current ? { backgroundColor: 'var(--accent)' } : undefined}
          >
            {i + 1}
          </button>
        ))}
      </div>

      {/* Question */}
      <div className="rounded-2xl p-5 mb-5" style={{ backgroundColor: 'var(--bg-elevated)', border: '1px solid var(--border)' }}>
        <p className="text-xs font-medium uppercase tracking-wide mb-2" style={{ color: 'var(--accent)' }}>{q.topic}</p>
        <p className="text-white text-base leading-relaxed">{q.question}</p>
      </div>

      {/* Options */}
      <div className="space-y-2 mb-6">
        {OPTION_KEYS.map((opt) => {
          const isSelected = answers[q.id] === opt
          return (
            <button
              key={opt}
              id={`exam-option-${opt}`}
              onClick={() => setAnswers((prev) => ({ ...prev, [q.id]: opt }))}
              className={`w-full text-left px-4 py-3 rounded-xl border text-sm transition-all duration-150 flex items-center gap-3 ${
                isSelected
                  ? 'text-white'
                  : 'border-white/10 bg-white/[0.03] text-slate-300 hover:border-white/20'
              }`}
              style={isSelected ? { backgroundColor: 'var(--accent-soft)', borderColor: 'rgba(90,127,245,0.2)' } : undefined}
            >
              <span className="w-6 h-6 rounded-full border border-current flex items-center justify-center text-xs font-bold flex-shrink-0 uppercase">
                {opt}
              </span>
              {optionLabels[opt]}
            </button>
          )
        })}
      </div>

      {/* Navigation */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => setCurrent((c) => Math.max(0, c - 1))}
          disabled={current === 0}
          className="btn-outline py-2 px-4 text-sm disabled:opacity-40"
        >
          Previous
        </button>
        {current < questions.length - 1 ? (
          <button
            id="exam-next-btn"
            onClick={() => setCurrent((c) => c + 1)}
            className="btn-primary py-2 px-4 text-sm"
          >
            Next <ChevronRight className="w-4 h-4" />
          </button>
        ) : (
          <button
            id="submit-exam-btn"
            onClick={finishExam}
            className="btn-primary py-2 px-4 text-sm bg-emerald-600"
          >
            Submit Exam
          </button>
        )}
      </div>
    </div>
  )
}
