"""Add state to chat_sessions

Revision ID: 9a02856af166
Revises: 44ab13ab1996
Create Date: 2026-08-19 16:01:06.247894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a02856af166'
down_revision: Union[str, None] = '44ab13ab1996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'state')
    # ### end Alembic commands ###
