"""add_my_study_gpt_fields

Revision ID: a636d90fd135
Revises: 9a02856af166
Create Date: 2026-08-21 11:23:13.980448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a636d90fd135'
down_revision: Union[str, None] = '9a02856af166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('source_type', sa.String(), server_default='curriculum', nullable=False))
    op.add_column('quiz_sessions', sa.Column('source_type', sa.String(), server_default='curriculum', nullable=False))
    op.add_column('space_documents', sa.Column('material_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space_documents', 'material_type')
    op.drop_column('quiz_sessions', 'source_type')
    op.drop_column('quiz_questions', 'source_type')
    # ### end Alembic commands ###
