"""add_documents

Revision ID: f059c1b9b792
Revises: c9e2f54a8b37
Create Date: 2026-07-10 18:02:00.913823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f059c1b9b792'
down_revision: Union[str, None] = 'c9e2f54a8b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['learning_spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_documents_id'), 'space_documents', ['id'], unique=False)
    op.create_index(op.f('ix_space_documents_space_id'), 'space_documents', ['space_id'], unique=False)
    op.drop_index('ix_space_notes_space_id', table_name='space_notes')
    op.create_index(op.f('ix_space_notes_space_id'), 'space_notes', ['space_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_notes_space_id'), table_name='space_notes')
    op.create_index('ix_space_notes_space_id', 'space_notes', ['space_id'], unique=False)
    op.drop_index(op.f('ix_space_documents_space_id'), table_name='space_documents')
    op.drop_index(op.f('ix_space_documents_id'), table_name='space_documents')
    op.drop_table('space_documents')
    # ### end Alembic commands ###
