export const NEET_TOPICS = {
  "Physics": [
    "Physical World and Units", "Motion in a Straight Line", "Motion in a Plane",
    "Laws of Motion", "Work, Energy and Power", "System of Particles & Rotational Motion",
    "Gravitation", "Mechanical Properties of Solids", "Mechanical Properties of Fluids",
    "Thermal Properties of Matter", "Thermodynamics", "Kinetic Theory of Gases",
    "Oscillations", "Waves", "Electric Charges and Fields", "Electrostatic Potential and Capacitance",
    "Current Electricity", "Moving Charges and Magnetism", "Magnetism and Matter",
    "Electromagnetic Induction", "Alternating Current", "Electromagnetic Waves",
    "Ray Optics and Optical Instruments", "Wave Optics",
    "Dual Nature of Radiation and Matter", "Atoms", "Nuclei",
    "Semiconductor Electronics", "Communication Systems",
  ],
  "Chemistry": [
    "Some Basic Concepts of Chemistry", "Structure of Atom", "Classification of Elements",
    "Chemical Bonding and Molecular Structure", "States of Matter", "Thermodynamics",
    "Equilibrium", "Redox Reactions", "Hydrogen",
    "The s-Block Elements", "The p-Block Elements", "Organic Chemistry Basics",
    "Hydrocarbons", "Environmental Chemistry",
    "Solid State", "Solutions", "Electrochemistry", "Chemical Kinetics",
    "Surface Chemistry", "General Principles of Extraction of Metals",
    "The p-Block Elements (Period 3)", "The d and f Block Elements",
    "Coordination Compounds", "Haloalkanes and Haloarenes",
    "Alcohols, Phenols and Ethers", "Aldehydes, Ketones and Carboxylic Acids",
    "Amines", "Biomolecules", "Polymers", "Chemistry in Everyday Life",
  ],
  "Botany": [
    "The Living World", "Biological Classification", "Plant Kingdom",
    "Morphology of Flowering Plants", "Anatomy of Flowering Plants",
    "Cell: The Unit of Life", "Cell Cycle and Cell Division",
    "Photosynthesis in Higher Plants", "Respiration in Plants",
    "Plant Growth and Development", "Transport in Plants",
    "Mineral Nutrition", "Sexual Reproduction in Flowering Plants",
    "Principles of Inheritance and Variation", "Molecular Basis of Inheritance",
    "Evolution", "Strategies for Enhancement in Food Production",
    "Microbes in Human Welfare", "Biotechnology: Principles and Processes",
    "Biotechnology and its Applications", "Organisms and Populations",
    "Ecosystem", "Biodiversity and Conservation", "Environmental Issues",
  ],
  "Zoology": [
    "Animal Kingdom", "Structural Organisation in Animals",
    "Human Physiology: Digestion and Absorption",
    "Human Physiology: Breathing and Exchange of Gases",
    "Human Physiology: Body Fluids and Circulation",
    "Human Physiology: Excretory Products and their Elimination",
    "Human Physiology: Locomotion and Movement",
    "Human Physiology: Neural Control and Coordination",
    "Human Physiology: Chemical Coordination and Integration",
    "Human Reproduction", "Reproductive Health",
    "Genetics and Evolution", "Human Health and Disease",
    "Animal Husbandry", "Biodiversity and Conservation",
    "Environmental Issues",
  ],
};

export const TNPSC_TOPICS = {
  "History": [
    "Indus Valley Civilisation", "Vedic Age", "Jainism and Buddhism",
    "Mauryan Empire", "Gupta Empire", "Sangam Age",
    "Medieval Tamil Nadu", "Delhi Sultanate", "Mughal Empire",
    "Maratha Empire", "Advent of Europeans", "British East India Company",
    "Social Reform Movements", "Indian National Congress",
    "Non-Cooperation Movement", "Civil Disobedience Movement",
    "Quit India Movement", "Partition and Independence",
    "Post-Independence India", "Tamil Nadu History",
  ],
  "Geography": [
    "Universe and Solar System", "Earth — Structure and Interior",
    "Landforms — Mountains, Plateaus, Plains",
    "Rocks and Minerals", "Earthquakes and Volcanoes",
    "Atmosphere — Composition and Layers", "Weather and Climate",
    "Monsoon in India", "Ocean Currents and Tides",
    "Natural Vegetation and Wildlife", "Population Geography",
    "Agriculture in India", "Industries in India",
    "Transport and Communication", "Indian Rivers and Lakes",
    "Tamil Nadu — Physical Features", "Tamil Nadu — Agriculture",
    "Tamil Nadu — Industries", "Environmental Geography",
    "World Geography — Continents and Oceans",
  ],
  "Polity": [
    "Making of the Indian Constitution", "Preamble", "Fundamental Rights",
    "Directive Principles of State Policy", "Fundamental Duties",
    "Parliament — Lok Sabha and Rajya Sabha", "President and Vice President",
    "Prime Minister and Council of Ministers", "Supreme Court",
    "High Courts and Subordinate Courts", "State Legislature",
    "Governor", "Chief Minister and Cabinet",
    "Local Self-Government — Panchayati Raj", "Urban Local Bodies",
    "Election Commission", "CAG and UPSC",
    "Centre-State Relations", "Emergency Provisions",
    "Constitutional Amendments", "Tamil Nadu Polity",
  ],
  "Economics": [
    "Basic Economic Concepts", "National Income",
    "Money and Banking", "Inflation and Deflation",
    "Indian Budget — Union and State", "Five Year Plans",
    "Agriculture — Green Revolution", "Land Reforms in India",
    "Poverty and Unemployment", "Economic Reforms 1991",
    "WTO, IMF and World Bank", "Taxation in India",
    "Public Finance", "GDP and GNP",
    "Financial Inclusion and Digital Economy",
    "Tamil Nadu Economy", "Government Schemes — State and Centre",
    "Human Development Index", "Sustainable Development Goals",
  ],
  "Science": [
    "Motion and Force", "Work, Energy and Power",
    "Sound and Light", "Heat and Temperature",
    "Electricity and Magnetism", "Atomic Structure",
    "Periodic Table", "Chemical Bonding",
    "Acids, Bases and Salts", "Metals and Non-Metals",
    "Carbon Compounds", "Cell Biology",
    "Plant and Animal Kingdom", "Human Body Systems",
    "Nutrition and Health", "Disease and Immunity",
    "Environmental Science", "Space Science",
    "Inventions and Discoveries", "Science and Technology in India",
  ],
  "Current Affairs": [
    "National Events", "International Events",
    "Awards and Honours", "Sports",
    "Science and Technology", "Economy and Finance",
    "Government Schemes and Policies", "Environment",
    "Defence and Security", "Tamil Nadu Current Affairs",
    "Appointments and Resignations", "Books and Authors",
    "Important Days and Themes", "Summits and Conferences",
  ],
};

/**
 * Return the topic list for a given subject name.
 * Covers both NEET and TNPSC subjects.
 */
export const getTopics = (subject) => {
  return NEET_TOPICS[subject] || TNPSC_TOPICS[subject] || [];
};
